### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [lycantropos/rsrc#9]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary rsrc -w /tmp/ext rsrc==0.1.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting rsrc==0.1.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/551/df8f19949bd68/rsrc-0.1.1.tar.gz (6.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-egyvdk6m/rsrc/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-egyvdk6m/rsrc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-egyvdk6m/rsrc/pip-egg-info
         cwd: /tmp/pip-wheel-egyvdk6m/rsrc/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-egyvdk6m/rsrc/setup.py", line 10, in <module>
        install_requires = Path('requirements.txt').read_text()
      File "/usr/lib/python3.8/pathlib.py", line 1227, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/usr/lib/python3.8/pathlib.py", line 1213, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by lycantropos** [comment]
Sorry for a long response, by some reason I wasn't subscribed to notifications, will definitely fix that ASAP, thanks for the info.
